### ISSUE TITLE
Baza

### ISSUE THREAD

**Issue by jaanos** [Marsovc1/Pohodnistvo#2]
Vidim, da za svoj projekt uporabljate bazo SQLite. Za uspešno opravljanje projekta naj se aplikacija poveže na bazo PostgreSQL na strežniku `baza.fmf.uni-lj.si`, tako kot pri [vzorčnem projektu](https://github.com/jaanos/OPB-bottle) (uporabite eno od vaših baz `sem2020_*` in ustrezno nastavite pravice).

Opažam še, da se vam je na repozitorij izmuznila mapa `__pycache__`. V `.gitignore` sicer že obstaja ustrezna vrstica, tako da bo zadostovalo, da mapo pobrišete (lahko kar pobrišete datoteko v njej na GitHubu).

**Comment by kokosinekm** [comment]
Hvala za obvestilo.

Ob izvajanju sql stavkov nam aplikacija vedno vrne None. Ne vemo ali je problem ob povezavi na bazo v pohodnistvo.py ali v pravicah za 'javnost' na bazi PostgreSQL.

**Comment by jaanos** [comment]
Metoda `execute` ne vrne podatkov, pač pa samo izvede poizvedbo. Če želite pridobiti podatke, lahko uporabite zanko `for` na kurzorju (lahko tudi podaste kurzor predlogi in znotraj nje uporabite zanko), ali pa na kurzorju uporabite metodo `fetchall`, ki vrne seznam vseh (preostalih) vrstic, oziroma `fetchone`, ki vrne eno (naslednjo) vrstico (ali pa `None`, če ni več rezultatov).

**Comment by kokosinekm** [comment]
Hvala za pomoč, sem popravil in sedaj baza deluje.
