### ISSUE TITLE
Zaključek

### ISSUE THREAD

**Issue by kokosinekm** [Marsovc1/Pohodnistvo#3]
Zdi se nam, da baza deluje in nas zanima ali je potrebno kaj dodati oziroma popraviti?

**Comment by jaanos** [comment]
Projekt deluje, tako da bom dodal povezavo na repozitorij predmeta. Če se še niste, se lahko z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.

Imam še sledeče pripombe:

* V tabeli `obiskane` manjka glavni ključ - ta naj sestoji iz obeh referenc.

* V svoji kodi na več mestih kličete funkcijo `napaka403`. S tem sicer prikažete napako, a je brskalnik ne zazna kot take (uporabi se koda 200, tako kot običajno). Če želite sprožiti napako 403 (ali katero drugo), naredite `raise HTTPError(403)`. Seveda to naredite takoj, ko lahko zaznate napako (tj., ne delajte poizvedb, katerih rezultatov ne potrebujete) - ukaz `raise` sproži navedeno napako in konča izvajanje funkcije.

* Pazite, da s svojimi poizvedbami ne pridobite več podatkov, kot jih res potrebujete. Sledeče bi lahko npr. naredili bolj učinkovito:
https://github.com/Marsovc1/Pohodnistvo/blob/e0789d3f1c7574673afc07e22fdb0bcd0a5c343f/pohodnistvo.py#L415-L425
```python
     #najvisji osvojen vrh 
     cur.execute(""" 
                 SELECT visina, ime FROM gore
                 JOIN obiskane ON id = id_gore
                 WHERE id_osebe = %s
                 ORDER BY gore.visina DESC LIMIT 1
                 """, (identiteta,)) 
     najvisji_osvojen_vrh = cur.fetchone() 
     if najvisji_osvojen_vrh is None:
         najvisji_osvojen_vrh = (None, None) 
```
Podobno bi tukaj zadostovala samo ena poizvedba z ustreznim `JOIN`om:
https://github.com/Marsovc1/Pohodnistvo/blob/e0789d3f1c7574673afc07e22fdb0bcd0a5c343f/pohodnistvo.py#L436-L451
```python
     cur.execute(""" 
                 SELECT ime, visina, gorovje, drzava, leto_pristopa FROM gore
                 JOIN obiskane ON id = id_gore
                 WHERE id_osebe = %s
                 ORDER BY ime
                 """, (identiteta, )) 
     vse_osvojene_gore = cur.fetchall() 
```
(pravzaprav bi lahko prejšnji podatek izluščili iz rezultata slednje poizvedbe).

* Desno zgoraj imate povezavo **Odjava** - ta naj se spremeni v **Prijava**, ko uporabnik ni prijavljen.

* Na seznamu društev je mogoče klikniti posamezno društvo, a navaden uporabnik do te strani nima dostopa. V tem primeru bi bilo bolje, če se povezava niti ne ustvari (tj., navaden uporabnik vidi samo ime društva) - sicer pa ne vidim razloga, zakaj uporabnik tega ne bi mogel videti.

* Smiselno bi bilo omogočiti uporabniku, da ureja seznam svojih osvojenih vrhov. Kolikor vidim, imate za to pripravljeno stran, ampak se povezava nanjo ne prikaže zaradi različnih tipov pri primerjanju. To lahko rešite tako, da eksplicitno poveste, ali je nek parameter število:
```python
@get('/osebe/<identiteta:int>')
def lastnosti_osebe(identiteta):
    ...
```

* Trenutno lahko uporabnik doda goro - morda bi to možnost pustili le administratorju.

* Slike ob straneh so previsoke in zato raztegnjene. Atribut `height` lahko izpustite, pa se bodo lepo prikazale.

* Svetujem še, da poskrbite, da bo aplikacijo mogoče zagnati tudi v Binderju. Za več podrobnosti glejte jan248/Borza#1.

**Comment by kokosinekm** [comment]
Mislm, da smo uspeli dodati vaše predloge.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
